<!DOCTYPE html>
<html lang="en">

<head>
    <title>Test Login</title>
    <!-- Bootstrap 5 -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- custom css -->
    <style>
        .popup_window {
            display: none;
            /* position: relative; */
            /* left: 0; */
            /* top: 0; */
            /* border: solid #627173 1px; */
            padding: 10px;
            background-color: #E6E6D6;
            font-family: "Lucida Console", "Courier New", Courier, monospace;
            text-align: left;
            font-size: 8pt;
            width: 500px;
            margin: 8px auto;
        }

        #show_detail_line {
            margin-top: 3ex;
            margin-bottom: 1ex;
        }

        #total_row {
            font-weight: bold;
        }

        .testcase {
            margin-left: 2em;
        }
    </style>
</head>

<body>
<div class="container">
    <!-- Heading -->
    <div class='mt-3'>
        <h2 class='text-uppercase'>Test Login</h2>
        
            <p class="fst-italic">Ini test login</p>
        
        <hr>
        <p>
            <strong>Start time:</strong>
            <span>2024-07-08, 09:45:25</span>
        </p>
        <p>
            <strong>Duration:</strong>
            <span>0:00:03.608743</span>
        </p>
        <p>
            <strong>Status:</strong>
            <span>Total: 8</span>
            
            
            
                <span>&#8212; Error: 8</span>
            
            
        </p>
    </div>

    <!-- Report -->
    <hr>
    <p id='show_detail_line'>
        <strong>Show:</strong>
        <a href='javascript:showCase(0)' class="btn btn-sm btn-outline-primary">Summary</a>
        <a href='javascript:showCase(1)' class="btn btn-sm btn-outline-danger">Failed</a>
        <a href='javascript:showCase(2)' class="btn btn-sm btn-outline-primary">All</a>
    </p>
    <table id='result_table' class='table table-sm table-hover table-responsive'>
        <thead id='header_row'>
        <tr>
            <th>Test Group/Test case</th>
            <th>Count</th>
            <th>Pass</th>
            <th>Fail</th>
            <th>Error</th>
            <th>Skip</th>
            <th>View</th>
        </tr>
        </thead>
        
            <tr class="fw-bold">
                <td>TestLogin</td>
                <th>0</th>
                <th>0</th>
                <th>0</th>
                <th>8</th>
                <th>0</th>
                <td><a href="javascript:showClassDetail('c1', '0')"
                       class="text-decoration-none">Detail</a>
                </td>
            </tr>

            
                <tr id='et1.1' class="
                table-warning
                ">
                    <td>
                        <div class='testcase'>test_login_admin</div>
                    </td>

                    <td colspan='6' class="text-center">
                        <!--css div popup start-->
                        
                            <a class="popup_link badge text-decoration-none
                            bg-warning text-black
                            " onfocus='this.blur();'
                               href="javascript:showTestDetail('div_et1.1')">error</a>

                            <div id='div_et1.1' class="popup_window">
                                <div style='text-align: right; color:red;cursor:pointer'>
                                    <a onfocus='this.blur();'
                                       onclick="document.getElementById('div_et1.1').style.display = 'none';">
                                        [x]
                                    </a>
                                </div>
                                <pre>et1.1: Traceback (most recent call last):
  File "D:\SEMESTER 8\TA\proj-ta\testing\test_login.py", line 26, in test_login_admin
    response = client.post(
               ^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 633, in post
    return super().post(
           ^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 1145, in post
    return self.request(
           ^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 516, in request
    return super().request(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 398, in handle_request
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 395, in handle_request
    portal.call(self.app, scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\anyio\from_thread.py", line 288, in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\anyio\from_thread.py", line 217, in _call_func
    retval = await retval_or_awaitable
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SEMESTER 8\TA\proj-ta\main.py", line 230, in login
    user = alter_auth(form_data.username, form_data.password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SEMESTER 8\TA\proj-ta\dependencies.py", line 46, in alter_auth
    user_by_username = get_user_by_username(username)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SEMESTER 8\TA\proj-ta\db.py", line 33, in get_user_by_username
    connection = pymysql.connect(host=DB_HOST,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 361, in __init__
    self.connect()
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 669, in connect
    self._request_authentication()
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 971, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 1062, in _process_auth
    pkt = self._read_packet()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'server_ta'@'180.244.134.243' (using password: YES)")
</pre>
                            </div>
                            <!--css div popup end-->
                        
                    </td>
                </tr>
            
                <tr id='et1.2' class="
                table-warning
                ">
                    <td>
                        <div class='testcase'>test_login_admin_failed</div>
                    </td>

                    <td colspan='6' class="text-center">
                        <!--css div popup start-->
                        
                            <a class="popup_link badge text-decoration-none
                            bg-warning text-black
                            " onfocus='this.blur();'
                               href="javascript:showTestDetail('div_et1.2')">error</a>

                            <div id='div_et1.2' class="popup_window">
                                <div style='text-align: right; color:red;cursor:pointer'>
                                    <a onfocus='this.blur();'
                                       onclick="document.getElementById('div_et1.2').style.display = 'none';">
                                        [x]
                                    </a>
                                </div>
                                <pre>et1.2: Traceback (most recent call last):
  File "D:\SEMESTER 8\TA\proj-ta\testing\test_login.py", line 35, in test_login_admin_failed
    response = client.post(
               ^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 633, in post
    return super().post(
           ^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 1145, in post
    return self.request(
           ^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 516, in request
    return super().request(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 398, in handle_request
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 395, in handle_request
    portal.call(self.app, scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\anyio\from_thread.py", line 288, in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\anyio\from_thread.py", line 217, in _call_func
    retval = await retval_or_awaitable
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SEMESTER 8\TA\proj-ta\main.py", line 230, in login
    user = alter_auth(form_data.username, form_data.password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SEMESTER 8\TA\proj-ta\dependencies.py", line 46, in alter_auth
    user_by_username = get_user_by_username(username)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SEMESTER 8\TA\proj-ta\db.py", line 33, in get_user_by_username
    connection = pymysql.connect(host=DB_HOST,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 361, in __init__
    self.connect()
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 669, in connect
    self._request_authentication()
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 971, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 1062, in _process_auth
    pkt = self._read_packet()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'server_ta'@'180.244.134.243' (using password: YES)")
</pre>
                            </div>
                            <!--css div popup end-->
                        
                    </td>
                </tr>
            
                <tr id='et1.3' class="
                table-warning
                ">
                    <td>
                        <div class='testcase'>test_login_reviewer_external</div>
                    </td>

                    <td colspan='6' class="text-center">
                        <!--css div popup start-->
                        
                            <a class="popup_link badge text-decoration-none
                            bg-warning text-black
                            " onfocus='this.blur();'
                               href="javascript:showTestDetail('div_et1.3')">error</a>

                            <div id='div_et1.3' class="popup_window">
                                <div style='text-align: right; color:red;cursor:pointer'>
                                    <a onfocus='this.blur();'
                                       onclick="document.getElementById('div_et1.3').style.display = 'none';">
                                        [x]
                                    </a>
                                </div>
                                <pre>et1.3: Traceback (most recent call last):
  File "D:\SEMESTER 8\TA\proj-ta\testing\test_login.py", line 71, in test_login_reviewer_external
    response = client.post(
               ^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 633, in post
    return super().post(
           ^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 1145, in post
    return self.request(
           ^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 516, in request
    return super().request(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 398, in handle_request
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 395, in handle_request
    portal.call(self.app, scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\anyio\from_thread.py", line 288, in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\anyio\from_thread.py", line 217, in _call_func
    retval = await retval_or_awaitable
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SEMESTER 8\TA\proj-ta\main.py", line 230, in login
    user = alter_auth(form_data.username, form_data.password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SEMESTER 8\TA\proj-ta\dependencies.py", line 46, in alter_auth
    user_by_username = get_user_by_username(username)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SEMESTER 8\TA\proj-ta\db.py", line 33, in get_user_by_username
    connection = pymysql.connect(host=DB_HOST,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 361, in __init__
    self.connect()
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 669, in connect
    self._request_authentication()
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 971, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 1062, in _process_auth
    pkt = self._read_packet()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'server_ta'@'180.244.134.243' (using password: YES)")
</pre>
                            </div>
                            <!--css div popup end-->
                        
                    </td>
                </tr>
            
                <tr id='et1.4' class="
                table-warning
                ">
                    <td>
                        <div class='testcase'>test_login_reviewer_external_failed</div>
                    </td>

                    <td colspan='6' class="text-center">
                        <!--css div popup start-->
                        
                            <a class="popup_link badge text-decoration-none
                            bg-warning text-black
                            " onfocus='this.blur();'
                               href="javascript:showTestDetail('div_et1.4')">error</a>

                            <div id='div_et1.4' class="popup_window">
                                <div style='text-align: right; color:red;cursor:pointer'>
                                    <a onfocus='this.blur();'
                                       onclick="document.getElementById('div_et1.4').style.display = 'none';">
                                        [x]
                                    </a>
                                </div>
                                <pre>et1.4: Traceback (most recent call last):
  File "D:\SEMESTER 8\TA\proj-ta\testing\test_login.py", line 80, in test_login_reviewer_external_failed
    response = client.post(
               ^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 633, in post
    return super().post(
           ^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 1145, in post
    return self.request(
           ^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 516, in request
    return super().request(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 398, in handle_request
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 395, in handle_request
    portal.call(self.app, scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\anyio\from_thread.py", line 288, in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\anyio\from_thread.py", line 217, in _call_func
    retval = await retval_or_awaitable
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SEMESTER 8\TA\proj-ta\main.py", line 230, in login
    user = alter_auth(form_data.username, form_data.password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SEMESTER 8\TA\proj-ta\dependencies.py", line 46, in alter_auth
    user_by_username = get_user_by_username(username)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SEMESTER 8\TA\proj-ta\db.py", line 33, in get_user_by_username
    connection = pymysql.connect(host=DB_HOST,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 361, in __init__
    self.connect()
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 669, in connect
    self._request_authentication()
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 971, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 1062, in _process_auth
    pkt = self._read_packet()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'server_ta'@'180.244.134.243' (using password: YES)")
</pre>
                            </div>
                            <!--css div popup end-->
                        
                    </td>
                </tr>
            
                <tr id='et1.5' class="
                table-warning
                ">
                    <td>
                        <div class='testcase'>test_login_reviewer_internal</div>
                    </td>

                    <td colspan='6' class="text-center">
                        <!--css div popup start-->
                        
                            <a class="popup_link badge text-decoration-none
                            bg-warning text-black
                            " onfocus='this.blur();'
                               href="javascript:showTestDetail('div_et1.5')">error</a>

                            <div id='div_et1.5' class="popup_window">
                                <div style='text-align: right; color:red;cursor:pointer'>
                                    <a onfocus='this.blur();'
                                       onclick="document.getElementById('div_et1.5').style.display = 'none';">
                                        [x]
                                    </a>
                                </div>
                                <pre>et1.5: Traceback (most recent call last):
  File "D:\SEMESTER 8\TA\proj-ta\testing\test_login.py", line 53, in test_login_reviewer_internal
    response = client.post(
               ^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 633, in post
    return super().post(
           ^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 1145, in post
    return self.request(
           ^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 516, in request
    return super().request(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 398, in handle_request
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 395, in handle_request
    portal.call(self.app, scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\anyio\from_thread.py", line 288, in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\anyio\from_thread.py", line 217, in _call_func
    retval = await retval_or_awaitable
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SEMESTER 8\TA\proj-ta\main.py", line 230, in login
    user = alter_auth(form_data.username, form_data.password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SEMESTER 8\TA\proj-ta\dependencies.py", line 46, in alter_auth
    user_by_username = get_user_by_username(username)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SEMESTER 8\TA\proj-ta\db.py", line 33, in get_user_by_username
    connection = pymysql.connect(host=DB_HOST,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 361, in __init__
    self.connect()
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 669, in connect
    self._request_authentication()
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 971, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 1062, in _process_auth
    pkt = self._read_packet()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'server_ta'@'180.244.134.243' (using password: YES)")
</pre>
                            </div>
                            <!--css div popup end-->
                        
                    </td>
                </tr>
            
                <tr id='et1.6' class="
                table-warning
                ">
                    <td>
                        <div class='testcase'>test_login_reviewer_internal_failed</div>
                    </td>

                    <td colspan='6' class="text-center">
                        <!--css div popup start-->
                        
                            <a class="popup_link badge text-decoration-none
                            bg-warning text-black
                            " onfocus='this.blur();'
                               href="javascript:showTestDetail('div_et1.6')">error</a>

                            <div id='div_et1.6' class="popup_window">
                                <div style='text-align: right; color:red;cursor:pointer'>
                                    <a onfocus='this.blur();'
                                       onclick="document.getElementById('div_et1.6').style.display = 'none';">
                                        [x]
                                    </a>
                                </div>
                                <pre>et1.6: Traceback (most recent call last):
  File "D:\SEMESTER 8\TA\proj-ta\testing\test_login.py", line 62, in test_login_reviewer_internal_failed
    response = client.post(
               ^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 633, in post
    return super().post(
           ^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 1145, in post
    return self.request(
           ^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 516, in request
    return super().request(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 398, in handle_request
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 395, in handle_request
    portal.call(self.app, scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\anyio\from_thread.py", line 288, in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\anyio\from_thread.py", line 217, in _call_func
    retval = await retval_or_awaitable
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SEMESTER 8\TA\proj-ta\main.py", line 230, in login
    user = alter_auth(form_data.username, form_data.password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SEMESTER 8\TA\proj-ta\dependencies.py", line 46, in alter_auth
    user_by_username = get_user_by_username(username)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SEMESTER 8\TA\proj-ta\db.py", line 33, in get_user_by_username
    connection = pymysql.connect(host=DB_HOST,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 361, in __init__
    self.connect()
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 669, in connect
    self._request_authentication()
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 971, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 1062, in _process_auth
    pkt = self._read_packet()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'server_ta'@'180.244.134.243' (using password: YES)")
</pre>
                            </div>
                            <!--css div popup end-->
                        
                    </td>
                </tr>
            
                <tr id='et1.7' class="
                table-warning
                ">
                    <td>
                        <div class='testcase'>test_login_staff</div>
                    </td>

                    <td colspan='6' class="text-center">
                        <!--css div popup start-->
                        
                            <a class="popup_link badge text-decoration-none
                            bg-warning text-black
                            " onfocus='this.blur();'
                               href="javascript:showTestDetail('div_et1.7')">error</a>

                            <div id='div_et1.7' class="popup_window">
                                <div style='text-align: right; color:red;cursor:pointer'>
                                    <a onfocus='this.blur();'
                                       onclick="document.getElementById('div_et1.7').style.display = 'none';">
                                        [x]
                                    </a>
                                </div>
                                <pre>et1.7: Traceback (most recent call last):
  File "D:\SEMESTER 8\TA\proj-ta\testing\test_login.py", line 44, in test_login_staff
    response = client.post(
               ^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 633, in post
    return super().post(
           ^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 1145, in post
    return self.request(
           ^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 516, in request
    return super().request(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 398, in handle_request
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 395, in handle_request
    portal.call(self.app, scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\anyio\from_thread.py", line 288, in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\anyio\from_thread.py", line 217, in _call_func
    retval = await retval_or_awaitable
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SEMESTER 8\TA\proj-ta\main.py", line 230, in login
    user = alter_auth(form_data.username, form_data.password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SEMESTER 8\TA\proj-ta\dependencies.py", line 46, in alter_auth
    user_by_username = get_user_by_username(username)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SEMESTER 8\TA\proj-ta\db.py", line 33, in get_user_by_username
    connection = pymysql.connect(host=DB_HOST,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 361, in __init__
    self.connect()
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 669, in connect
    self._request_authentication()
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 971, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 1062, in _process_auth
    pkt = self._read_packet()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'server_ta'@'180.244.134.243' (using password: YES)")
</pre>
                            </div>
                            <!--css div popup end-->
                        
                    </td>
                </tr>
            
                <tr id='et1.8' class="
                table-warning
                ">
                    <td>
                        <div class='testcase'>test_login_superadmin</div>
                    </td>

                    <td colspan='6' class="text-center">
                        <!--css div popup start-->
                        
                            <a class="popup_link badge text-decoration-none
                            bg-warning text-black
                            " onfocus='this.blur();'
                               href="javascript:showTestDetail('div_et1.8')">error</a>

                            <div id='div_et1.8' class="popup_window">
                                <div style='text-align: right; color:red;cursor:pointer'>
                                    <a onfocus='this.blur();'
                                       onclick="document.getElementById('div_et1.8').style.display = 'none';">
                                        [x]
                                    </a>
                                </div>
                                <pre>et1.8: Traceback (most recent call last):
  File "D:\SEMESTER 8\TA\proj-ta\testing\test_login.py", line 17, in test_login_superadmin
    response = client.post(
               ^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 633, in post
    return super().post(
           ^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 1145, in post
    return self.request(
           ^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 516, in request
    return super().request(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 398, in handle_request
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\testclient.py", line 395, in handle_request
    portal.call(self.app, scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\anyio\from_thread.py", line 288, in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\anyio\from_thread.py", line 217, in _call_func
    retval = await retval_or_awaitable
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SEMESTER 8\TA\proj-ta\main.py", line 230, in login
    user = alter_auth(form_data.username, form_data.password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SEMESTER 8\TA\proj-ta\dependencies.py", line 46, in alter_auth
    user_by_username = get_user_by_username(username)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SEMESTER 8\TA\proj-ta\db.py", line 33, in get_user_by_username
    connection = pymysql.connect(host=DB_HOST,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 361, in __init__
    self.connect()
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 669, in connect
    self._request_authentication()
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 971, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 1062, in _process_auth
    pkt = self._read_packet()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\yuna\AppData\Roaming\Python\Python311\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'server_ta'@'180.244.134.243' (using password: YES)")
</pre>
                            </div>
                            <!--css div popup end-->
                        
                    </td>
                </tr>
            

        
        <tr id=' total_row'>
            <td>Total</td>
            <td>8</td>
            <td>0</td>
            <td>0</td>
            <td>8</td>
            <td>0</td>
            <td>&nbsp;</td>
        </tr>
    </table>

    <!-- Ending -->

</div>

<script type="text/javascript">
    output_list = Array();

    /* level - 0:Summary; 1:Failed; 2:All */
    function showCase(level) {
        let trs = document.getElementsByTagName("tr");
        for (let i = 0; i < trs.length; i++) {
            let tr = trs[i];
            let id = tr.id;

            let id_prefix = id.substring(0, 2);

            if (id_prefix === 'ft' || id_prefix === 'et') {
                if (level < 1) {
                    tr.classList.add('d-none');
                } else {
                    tr.classList.remove('d-none');
                }
            }
            if (id_prefix === 'pt' || id_prefix === 'st') {
                if (level > 1) {
                    tr.classList.remove('d-none');
                } else {
                    tr.classList.add('d-none');
                }
            }
        }
    }


    function showClassDetail(cid, count) {
        let id_list = Array(count);
        let toHide = 1;
        for (let i = 0; i < count; i++) {
            let tid0 = 't' + cid.substring(1) + '.' + (i + 1);
            let tid = 'f' + tid0;
            let tr = document.getElementById(tid);
            if (!tr) {
                tid = 'p' + tid0;
                tr = document.getElementById(tid);
            }
            id_list[i] = tid;
            if (tr.classList.contains('d-none')) {
                toHide = 0;
            }
        }
        for (let i = 0; i < count; i++) {
            let tid = id_list[i];
            if (toHide) {
                document.getElementById(tid).classList.add('d-none');
            } else {
                document.getElementById(tid).classList.remove('d-none');
            }
        }
    }


    function showTestDetail(div_id) {
        let details_div = document.getElementById(div_id)
        let displayState = details_div.style.display
        if (displayState !== 'block') {
            details_div.style.display = 'block'
        } else {
            details_div.style.display = 'none'
        }
    }
</script>

<script type="text/javascript">
    showCase(2);
</script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>


</body>

</html>